//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Coordinates { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> Completed { get; set; }
        public Nullable<bool> Private { get; set; }
        public string UserId { get; set; }
        public string Length { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
